name: Nuitka Action Test

on:
  push:
    branches: [ main ]

jobs:
  build-with-pip-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Test Nuitka Build
        uses: martinmiglio/Nuitka-Action@feature/dependency-caching
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          output-dir: dist
          assume-yes-for-downloads: true
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuitka-build
          path: dist
  build-with-nuitka-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Test Nuitka Build
        uses: martinmiglio/Nuitka-Action@feature/build-caching
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          output-dir: dist
          assume-yes-for-downloads: true
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuitka-build
          path: dist
