name: Nuitka Action Test

on:
  push:
    tags:
      - "*"

jobs:
  build-with-nuitka-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test Nuitka Build with Build Cache
        uses: martinmiglio/Nuitka-Action@feature/build-caching
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          output-dir: dist
          assume-yes-for-downloads: true
          mingw64: true # Only for Windows
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuitka-build-${{ matrix.os }}-${{matrix.python-version}}.zip
          path: dist
